apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/alertmanager/metrics'
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30001
      protocol: TCP
      name: webui
  selector:
    app: alertmanager